//
//  StringRes.swift
//  Created by YPY Global on 3/7/19.
//  Copyright © 2019 YPY Global. All rights reserved.
//

import Foundation
public class StringRes {
    
    static let otp_title = "otp_title"
    static let otp_info = "otp_info"
    static let request_otp = "request_otp"
    static let verify_otp = "verify_otp"
    
    static let app_name = "app_name"
    static let downloading_in_background = "downloading_in_background"
    static let public_image = "public.image"
    static let null_value = "null_value"
    static let gender_male = "gender_male"
    static let gender_female = "gender_female"
    static let date_of_birth_required = "date_of_birth_required"
    static let first_name_required = "first_name_required"
    static let last_name_required = "last_name_required"
    static let profile_no_data = "profile_no_data"
    static let friend_no_like = "friend_no_like"
    static let profile_no_short = "profile_no_short"
    static let profile_no_likes = "profile_no_likes"
    static let title_copyright = "title_copyright"
    static let title_home_screen = "title_home_screen"
    static let title_unknown = "title_unknown"
    
    static let title_tab_discover = "title_tab_discover"
    static let title_tab_shows = "title_tab_shows"
    static let title_tab_library = "title_tab_library"
    static let title_tab_profile = "title_tab_profile"
    static let title_tab_categories = "title_tab_categories"
    static let title_tab_records = "title_tab_records"
    static let title_tab_notify = "title_tab_notify"
    
    static let title_favorite = "title_favorite"
    
    static let title_privacy_policy = "title_privacy_policy"
    static let title_term_of_use = "title_term_of_use"
    static let title_tell_a_friend = "title_tell_a_friend"
    static let title_rate_us = "title_rate_us"
    static let title_visit_fb = "title_visit_fb"
    static let title_visit_twitter = "title_visit_twitter"
    static let title_visit_website = "title_visit_website"
    static let title_visit_insta = "title_visit_insta"
    static let title_contact_us = "title_contact_us"
    
    static let array_profiles:[String] = ["title_update_premium","title_rate_us","title_tell_a_friend"
                                        ,"title_contact_us","title_visit_website","title_visit_fb","title_visit_insta"
                                        ,"title_visit_twitter","title_privacy_policy","title_term_of_use"]
    
    static let title_no_data = "title_no_data"
    static let info_connect_to_play = "info_connect_to_play"
    static let info_play_error = "info_play_error"
    static let info_radio_ended_sub = "info_radio_ended_sub"
    static let info_radio_ended_title = "info_radio_ended_title"
    static let info_radio_error = "info_radio_error"
    static let title_information = "title_information"
    
    static let format_share_app = "format_share_app"
    static let format_content_share = "format_content_share"
    static let format_bitrate = "format_bitrate"
    
    static let format_minutes = "format_minutes"
    static let format_minute = "format_minute"
    
    static let info_error_connect = "info_error_connect"
    static let title_setting = "title_setting"
    static let title_cancel = "title_cancel"
    static let title_ok = "title_ok"
    static let title_report = "title_report"
    static let title_off = "title_off"
    static let title_sleep_mode = "title_sleep_mode"
    static let title_done = "title_done"
    static let title_back = "title_back"
    static let title_confirm = "title_confirm"
    static let title_options = "title_options"
    
    static let event_info_future = "event_info_future"
    static let event_info_past = "event_info_later"
    static let event_info_present = "event_info_present"
    static let event_info_now = "event_info_now"
    
    static let title_search = "title_search"
    static let title_error = "title_error"


    static let info_loading = "info_loading"
    static let title_go_to_setting = "title_go_to_setting"
    static let title_setting_ads = "title_setting_ads"
    static let title_save = "title_save"
        
    static let title_downloads = "title_downloads"
    static let title_remove_downloads = "title_remove_downloads"
    static let title_download_now = "title_download_now"
    static let title_delete = "title_delete"
    static let info_delete_file = "info_delete_file"
    static let title_downloading = "title_downloading"
    static let title_loading = "title_loading"
    static let info_download_error = "info_download_error"
    static let info_sdcard_error = "info_sdcard_error"
    static let info_already_file_downloaded = "info_already_file_downloaded"
    static let info_saved_song_success = "info_saved_song_success"
    static let info_delete_success = "info_delete_success"
    static let info_deleted_error = "info_deleted_error"
    static let info_process_loading = "info_process_loading"
    static let title_share = "title_share"
    
    //Help string
    static let array_title_helps:[String] = ["title_help1","title_help2","title_help3","title_help4", "title_help5"]
    static let array_info_helps:[String] = ["info_help1","info_help2","info_help3","info_help4","info_help5"]
    
    static let title_skip = "title_skip";
    static let title_next = "title_next";
    static let title_join_now = "title_join_now";
    
    //IAP string
    static let array_product_ids:[String] = ["product_id1","product_id2","product_id3"]
    static let array_prices:[String] = ["price_1","price_2","price_3"]
    static let array_members:[String] = ["title_member_1","title_member_2","title_member_3"]
    static let array_date_times:[String] = ["title_datetime_1","title_datetime_2","title_datetime_3"]
    
    static let title_payment = "title_payment"
    static let info_no_receipt = "info_no_receipt"
    static let info_receipt_verify_failed = "info_receipt_verify_failed"
    static let info_purchase_expired = "info_purchase_expired"
    static let info_purchase_notpurchased = "info_purchase_notpurchased"

    static let title_client_invalid = "title_client_invalid"
    static let title_payment_cancelled = "title_payment_cancelled"

    static let info_payment_invalid = "info_payment_invalid"
    static let info_payment_not_allowed = "info_payment_not_allowed"

    static let info_store_product_not_available = "info_store_product_not_available"
    static let info_cloud_service_permission_denied = "info_cloud_service_permission_denied"
    static let info_cloud_service_revoked = "info_cloud_service_revoked"

    //restore purchase
    static let title_restore_failed = "title_restore_failed"
    static let info_restore_success = "info_restore_success"
    static let info_restore_noproduct = "info_restore_noproduct"

    static let title_purchase_success = "title_purchase_success"
    static let title_purchase_error = "title_purchase_error"
    static let info_thanks_purchasing = "info_thanks_purchasing"
    static let info_network_error_purchase = "info_network_error_purchase"
    
    static let title_restore_purchase = "title_restore_purchase"
    static let format_eula = "format_eula"
    
    //login text
    static let info_tap_login = "info_tap_login"
    static let format_empty_field = "format_empty_field"
    static let format_special_field = "format_special_field"
    static let title_forget_password = "title_forget_password"
    static let info_password_not_match = "info_password_not_match"
    static let info_password_current_not_match = "info_password_current_not_match"
    static let info_password_short = "info_password_short"
    static let info_register_success = "info_register_success"
    static let info_login_success = "info_login_success"
    static let info_request_login = "info_request_login"
    static let info_request_login_again = "info_request_login_again"
    static let info_reset_successfully = "info_reset_successfully"
    static let title_user_name = "title_user_name"
    static let title_display_name = "title_display_name"
    static let title_password = "title_password"
    static let title_email = "title_email"
    static let info_hint_forget_user_name = "info_hint_forget_user_name"
    static let title_confirm_pass = "title_confirm_pass"
    static let title_hint_password = "title_hint_password"
    static let title_hint_confirm_password = "title_hint_confirm_password"
    static let title_hint_email = "title_hint_email"
    static let title_sign_in = "title_sign_in"
    static let title_sign_up = "title_sign_up"
    static let title_sign_out = "title_sign_out"
    static let title_skip_login = "title_skip_login"
    
    static let title_create_account = "title_create_account"
    static let title_submit = "title_submit"
    static let title_logout = "title_logout"
    static let title_reset_password = "title_reset_password"
    static let info_update_done = "info_update_done"
    static let info_reset_done = "info_reset_done"
    static let info_profile_updated = "info_profile_updated"
    static let info_update_profile_error = "info_update_profile_error"
    static let info_wrong_user_pass = "info_wrong_user_pass"
    static let info_logout = "info_logout"
    static let info_sign_out_successfully = "info_sign_out_successfully"
    
    static let title_just_now = "title_just_now"
    static let title_second_ago = "title_second_ago"
    static let title_a_minute_ago = "title_a_minute_ago"
    static let title_minute_ago = "title_minute_ago"
    static let title_a_hour_ago = "title_a_hour_ago"
    static let title_hour_ago = "title_hour_ago"
    static let title_yester_day = "title_yester_day"
    static let title_day_ago = "title_day_ago"
    static let title_last_week = "title_last_week"
    static let title_weeks_ago = "title_weeks_ago"
    static let title_last_month = "title_last_month"
    static let title_month_ago = "title_month_ago"
    static let title_last_year = "title_last_year"
    static let title_year_ago = "title_year_ago"
    
    static let format_mins = "format_mins"
    static let format_min = "format_min"
    
    static let format_sec = "format_sec"
    static let format_secs = "format_secs"
    
    static let info_no_favorite = "info_no_favorite"
    
    static let title_featured_stories = "title_featured_stories"
    static let title_play_all = "title_play_all"
    
    static let format_episodes = "format_episodes"
    static let format_episode = "format_episode"
    
    static let info_premium_member = "info_premium_member"
    static let title_update_premium = "title_update_premium"
    static let info_listen_premium = "info_listen_premium"
    static let title_buy_now = "title_buy_now"
    static let format_info_member = "format_info_member"
    static let format_remove_ads = "format_remove_ads"
    static let format_removed_ads = "format_removed_ads"
    static let info_updating_member = "info_updating_member"
  
    static let title_add_favorite = "title_add_favorite"
    static let info_added_favorite = "info_added_favorite"
    static let title_remove_favorite = "title_remove_favorite"
    static let info_removed_favorite = "info_removed_favorite"
    static let title_no_description = "title_no_description"
    
    static let info_lose_internet = "info_lose_internet"
    static let info_email_invalid = "info_email_invalid"
    static let info_server_error = "info_server_error"
    static let info_not_activated_account = "info_not_activated_account"
    static let info_sign_in_successfully = "info_sign_in_successfully"
    static let info_reset_pass_success = "info_reset_pass_success"
    static let info_update_purchase_success = "info_update_purchase_success"
    
    static let title_subscribe = "title_subscribe"
    static let title_subscribed = "title_subscribed"
    static let format_title_community = "format_title_community"
    static let format_title_comment = "format_title_comment"
    static let info_hint_review = "info_hint_review"
    static let info_hint_comment = "info_hint_comment"
    static let info_login_to_add_review = "info_login_to_add_review"
    static let info_login_to_add_comment = "info_login_to_add_comment"
    static let info_delete_review = "info_delete_review"
    static let info_delete_comment = "info_delete_comment"
    static let info_data_error = "info_data_error"
    static let info_subscribed_successfully = "info_subscribed_successfully"
    static let info_unsubscribed_successfully = "info_unsubscribed_successfully"
    
    static let title_podcasts = "title_podcasts"
    static let title_stories = "title_stories"
    static let title_audio_books = "title_audio_books"
    static let title_my_subscriptions = "title_my_subscriptions"
    static let info_login_get_subscriptions = "info_login_get_subscriptions"
    
    static let title_follow = "title_follow"
    static let title_unfollow = "title_unfollow"
    static let info_follow_successfully = "info_follow_successfully"
    static let info_unfollow_successfully = "info_unfollow_successfully"
    
    static let format_stories = "format_stories"
    static let format_story = "format_story"
    static let title_no_story = "title_no_story"
    static let title_no_episode = "title_no_episode"
    static let title_my_stories = "title_my_stories"
    static let title_no_show = "title_no_show"
    static let format_title_story = "format_title_story"
    static let title_record_story = "title_record_story"
    static let title_story_title = "title_story_title"
    static let title_series_title = "title_series_title"
    static let title_explicit_content = "title_explicit_content"
    
    //UPLOAD STORY
    static let title_upload_story = "title_upload_story"
    static let title_start_recording = "title_start_recording"
    static let title_stop_recording = "title_stop_recording"
    static let title_record_again = "title_record_again"
    static let info_recording_again = "info_recording_again"
    static let info_stop_record = "info_stop_record"
    static let info_record_back = "info_record_back"
    static let info_recording_error = "info_recording_error"
    
    static let format_maximum_minute = "format_maximum_minute"
    static let info_upload_file_error = "info_upload_file_error"
    static let info_upload_file_success = "info_upload_file_success"
    static let info_upload_file_when_recording = "info_upload_file_when_recording"
    static let title_delete_story = "title_delete_story"
    static let info_delete_story = "info_delete_story"
    static let info_delete_story_success = "info_delete_story_success"
    static let info_delete_story_error = "info_delete_story_error"
    
    static let info_permission_denied = "info_permission_denied"
    static let info_permission_unknow_error = "info_permission_unknow_error"
    static let title_yes = "title_yes"
    static let info_select_image_error = "info_select_image_error"
    static let info_change_avatar = "info_change_avatar"
    
    static let info_change_avatar_success = "info_change_avatar_success"
    static let info_change_avatar_error = "info_change_avatar_error"
    
    
    static let format_follower = "format_follower"
    static let format_followers = "format_followers"
    static let format_following = "format_following"
    
    static let title_tab_followers = "title_tab_followers"
    static let title_tab_following = "title_tab_following"
    static let title_tab_who_to_follow = "title_tab_who_to_follow"
    
    static let format_like = "format_like"
    static let format_likes = "format_likes"
    
    static let format_comment = "format_comment"
    static let format_comments = "format_comments"
    static let title_tags = "title_tags"
    static let title_trending_show = "title_trending_show"
    static let format_with = "format_with"
    static let info_no_suggest_story = "info_no_suggest_story"
    
    static let title_creator_support = "title_creator_support"
    static let info_confirm_support = "info_confirm_support"
    static let title_continue = "title_continue"
    static let title_support = "title_support"
    static let info_tweet_share = "info_tweet_share"
    static let title_share_twitter = "title_share_twitter"
    static let title_story_tags = "title_story_tags"
    static let title_story_category = "title_story_category"
    static let title_story_language = "title_story_language"
    static let info_no_story_language = "info_no_story_language"
    static let info_no_story_category = "info_no_story_category"
    static let title_tell_story = "title_tell_story"
    static let title_story_series = "title_story_series"
    static let title_select_country = "title_select_country"
    static let title_select_language = "title_select_language"
    
    static let title_trending_users = "title_trending_users"
    static let title_popular_topics = "title_popular_topics"
    static let title_your_story = "title_your_story"
    static let title_explore_stories = "title_explore_stories"
    static let title_event_title = "title_event_title"
    static let title_event_category = "title_event_category"
    static let info_create_event_successfully = "info_create_event_successfully"
    static let title_event_scheduled = "title_event_scheduled"
    static let info_share_event_scheduled = "info_share_event_scheduled"
    static let title_menu_record_voice = "title_menu_record_voice"
    static let title_menu_create = "title_menu_create"
    static let title_menu_live_voice = "title_menu_live_voice"
    static let title_submit_podcast = "title_submit_podcast"
    static let title_accept_join = "title_accept_join"
    static let info_be_first_one = "info_be_first_one"
    static let format_listeners = "format_listeners"
    static let format_listener = "format_listener"
    static let title_manage = "title_manage"
    static let title_remove_me = "title_remove_me"
    static let title_notify_me = "title_notify_me"
    static let info_event_error = "info_event_error"
    
    static let title_social_tag_deep_link = "title_social_tag_deep_link"
    static let info_social_tag_deep_link = "info_social_tag_deep_link"
    static let info_error_deep_link = "info_error_deep_link"
    static let info_notify_me = "info_notify_me"
    static let info_added_listener = "info_added_listener"
    static let info_removed_listener = "info_removed_listener"
    static let info_join_now = "info_join_now"
    
    static let title_my_events = "title_my_events"
    static let title_live_events = "title_live_events"
    static let title_upcoming_events = "title_upcoming_events"
    static let title_past_events = "title_past_events"
    static let info_remove_me = "info_remove_me"
    static let format_title_event = "format_title_event"
    
    static let info_send_audio_start = "info_send_audio_start"
    static let info_send_audio_stop = "info_send_audio_stop"
    static let info_send_audio_error = "info_send_audio_error"
    static let info_stop_audio_error = "info_stop_audio_error"
    static let info_invite_error = "info_invite_error"
    static let info_invite_success = "info_invite_success"
    static let info_kicked_off_success = "info_kicked_off_success"
    static let info_updated_error = "info_updated_error"
    static let format_update_speaker = "format_update_speaker"
    static let format_update_no_speaker = "format_update_no_speaker"
    static let info_send_request_success = "info_send_request_success"
    static let info_send_request_error = "info_send_request_error"
    static let title_invitation = "title_invitation"
    static let format_invite_user = "format_invite_user"
    static let title_accept = "title_accept"
    static let info_declined_event = "info_declined_event"
    static let info_leave_event = "info_leave_event"
    static let info_event_stop = "info_event_stop"
    static let info_confirm_leave = "info_confirm_leave"
    static let title_leave = "title_leave"
    static let format_request_speaker = "format_request_speaker"
    static let title_edit = "title_edit"
    static let format_host_remove_speaker = "format_host_remove_speaker"
    static let format_host_accept_speaker = "format_host_accept_speaker"
    static let format_host_decline_speaker = "format_host_decline_speaker"
    static let info_my_kicked_off = "info_my_kicked_off"
    static let title_send_a_tip = "title_send_a_tip"
    static let title_kick_off = "title_kick_off"
    static let title_invited = "title_invited"
    static let title_invite = "title_invite"
    static let info_no_data_find_user = "info_no_data_find_user"
    static let info_no_speaker =  "info_no_speaker"
    static let title_permission = "title_permission"
    static let info_confirm_turn_on_speaker = "info_confirm_turn_on_speaker"
    static let info_confirm_turn_off_speaker = "info_confirm_turn_off_speaker"
    static let title_remove = "title_remove"
    static let title_decline = "title_decline"
    static let info_reset_raise_hand = "info_reset_raise_hand"
    static let info_duplicate_podcast_feed = "info_duplicate_podcast_feed"
    static let info_submit_podcast = "info_submit_podcast"
    static let info_error = "info_error"
    static let info_input_required = "info_input_required"
    static let info_feed_url_required_msg = "info_feed_url_required_msg"
    static let info_country_required_msg = "info_country_required_msg"
    static let info_submit_label = "info_submit_label"
    static let info_language_required_msg = "info_language_required_msg"
    
}
